proyecto/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('prueba/',include('prueba.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prueba/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("",views.home_prueba, name='home_prueba'),
    path("realizar_prueba/", views.realizar_prueba, name="realizar_prueba"),
]

prueba/models.py
from django.db import models

# Create your models here.
class Prueba(models.Model):
    paciente = models.CharField(max_length=500, blank=False)
    fecha_nacimiento = models.DateField()
    respuesta1 = models.CharField(max_length=500, blank=False)
    respuesta2 = models.CharField(max_length=500, blank=False)
    respuesta3 = models.CharField(max_length=500, blank=False)
    respuesta4 = models.CharField(max_length=500, blank=False)
    respuesta5 = models.CharField(max_length=500, blank=False)
    respuesta6 = models.CharField(max_length=500, blank=False)
    respuesta7 = models.CharField(max_length=500, blank=False)
    respuesta8 = models.CharField(max_length=500, blank=False)
    respuesta9 = models.CharField(max_length=500, blank=False)
    respuesta10 = models.CharField(max_length=500, blank=False)
    respuesta11 = models.CharField(max_length=500, blank=False)
    respuesta12 = models.CharField(max_length=500, blank=False)
    respuesta13= models.CharField(max_length=500, blank=False)
    respuesta14 = models.CharField(max_length=500, blank=False)
    respuesta15 = models.CharField(max_length=500, blank=False)
    respuesta16 = models.CharField(max_length=500, blank=False)
    respuesta17 = models.CharField(max_length=500, blank=False)
    respuesta18 = models.CharField(max_length=500, blank=False)
    respuesta19 = models.CharField(max_length=500, blank=False)
    respuesta20 = models.CharField(max_length=500, blank=False)

    respuesta_hora = models.DateTimeField(auto_now_add=True)

    respuesta_video = models.FileField(upload_to='videos/respuestas',  blank=True)

    respuesta_emociones = models.CharField(max_length=1000,  blank=True)

    def __str__(self) -> str:
        return self.paciente

prueba/forms.py
from django import forms
from .models import Prueba

class PruebaForm(forms.ModelForm):

    class Meta:
        model = Prueba
        fields = '__all__'

proyecto/views.py
from django.shortcuts import render

def home(request):
    return render(request,'home.html')

prueba/views.py
from django.shortcuts import redirect, render
from .models import Prueba
from .forms import PruebaForm

def home_prueba(request):
    contexto = {}
    return render(request, 'home.html', contexto)


def realizar_prueba(request):
    if(request.method == "POST"):
        form = PruebaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home_prueba')
    
    else:
        pass

    contexto = {}
    return render(request,'realizar_prueba.html',contexto)

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gordon-ia</title>
</head>
<body>
    <h1>Bienvenido a Gordon IA</h1>
</body>
</html>

templates/realizar_prueba.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Realizar prueba</title>
</head>

<body>
    <div>
        <form method="post"  enctype="multipart/form-data">
            {% csrf_token %}

            <button type="button" id="boton">Comenzar</button>
            <br><br>

            <div id="preguntas" hidden>
                <label>Inrgese sus nombres y apellidos: </label>
                <input type="text" name="paciente">
                <br>


                <label>Fecha de nacimiento</label>
                <input type="date" name="fecha_nacimiento">
                <br>


                <label>¿Te has sentido triste en este dia?</label>
                <select name="respuesta1">
                    <option value="1">Uno</option>
                    <option value="2">Dos</option>
                    <option value="3">Tres</option>
                    <option value="4">Cuatro</option>
                </select>
                <br>

                <label>¿Te has seindo pesimo en este dia?</label>
                <select name="respuesta2">
                    <option value="1">Uno</option>
                    <option value="2">Dos</option>
                    <option value="3">Tres</option>
                    <option value="4">Cuatro</option>
                </select>
                <br>

                <label>¿Has sentido que has fracasado en lo que te has propuesto?</label>
                <select name="respuesta3">
                    <option value="1">Uno</option>
                    <option value="2">Dos</option>
                    <option value="3">Tres</option>
                    <option value="4">Cuatro</option>
                </select>
                <br>
                <label>¿Sientes que has perdido la sensacion de placer?</label>
                <select name="respuesta4">
                    <option value="1">Uno</option>
                    <option value="2">Dos</option>
                    <option value="3">Tres</option>
                    <option value="4">Cuatro</option>
                </select>
                <br>
                <label>¿Sientes culpa por algo?</label>
                <select name="respuesta5">
                    <option value="1">Uno</option>
                    <option value="2">Dos</option>
                    <option value="3">Tres</option>
                    <option value="4">Cuatro</option>
                </select>
                <br>
                <label>¿Has sentido un sentimiento de castigo?</label>
                <select name="respuesta6">
                    <option value="1">Uno</option>
                    <option value="2">Dos</option>
                    <option value="3">Tres</option>
                    <option value="4">Cuatro</option>
                </select>
                <br>
                <label>¿Te sientes disconforme con tu vida actualmente?</label>
                <select name="respuesta7">
                    <option value="1">Uno</option>
                    <option value="2">Dos</option>
                    <option value="3">Tres</option>
                    <option value="4">Cuatro</option>
                </select>
                <br>
                <label>¿Qué crees que deberias mejorar con respecto a tu vida?</label>
                <select name="respuesta8">
                    <option value="1">Uno</option>
                    <option value="2">Dos</option>
                    <option value="3">Tres</option>
                    <option value="4">Cuatro</option>
                </select>
                <br>
                <label>¿Has pensado alguna vez en el suicidio?</label>
                <select name="respuesta9">
                    <option value="1">Uno</option>
                    <option value="2">Dos</option>
                    <option value="3">Tres</option>
                    <option value="4">Cuatro</option>
                </select>
                <br>
                <label>¿Has llorado ultimamente (15 dias)?</label>
                <select name="respuesta10">
                    <option value="1">Uno</option>
                    <option value="2">Dos</option>
                    <option value="3">Tres</option>
                    <option value="4">Cuatro</option>
                </select>
                <br>
                <label>¿Te sientes agitado en situaciones incomodas?</label>
                <select name="respuesta11">
                    <option value="1">Uno</option>
                    <option value="2">Dos</option>
                    <option value="3">Tres</option>
                    <option value="4">Cuatro</option>
                </select>
                <br>
                <label>¿Has perdido el interes en tus estudios?</label>
                <select name="respuesta12">
                    <option value="1">Uno</option>
                    <option value="2">Dos</option>
                    <option value="3">Tres</option>
                    <option value="4">Cuatro</option>
                </select>
                <br>
                <label>¿Sientes dudas al tomar una decisión?</label>
                <select name="respuesta13">
                    <option value="1">Uno</option>
                    <option value="2">Dos</option>
                    <option value="3">Tres</option>
                    <option value="4">Cuatro</option>
                </select>
                <br>
                <label>¿Sientes que la energia con las que haces tus tareas a disminuido?</label>
                <select name="respuesta14">
                    <option value="1">Uno</option>
                    <option value="2">Dos</option>
                    <option value="3">Tres</option>
                    <option value="4">Cuatro</option>
                </select>
                <br>
                <label>¿Tienes problemas ara dormir?</label>
                <select name="respuesta15">
                    <option value="1">Uno</option>
                    <option value="2">Dos</option>
                    <option value="3">Tres</option>
                    <option value="4">Cuatro</option>
                </select>
                <br>
                <label>¿Te sientes irritado rapidamente (socialmente)?</label>
                <select name="respuesta16">
                    <option value="1">Uno</option>
                    <option value="2">Dos</option>
                    <option value="3">Tres</option>
                    <option value="4">Cuatro</option>
                </select>
                <br>
                <label>¿Sientes que ha cambiado tu apetito?</label>
                <select name="respuesta17">
                    <option value="1">Uno</option>
                    <option value="2">Dos</option>
                    <option value="3">Tres</option>
                    <option value="4">Cuatro</option>
                </select>
                <br>
                <label>¿Sientes dificultad al consetrarte?</label>
                <select name="respuesta18">
                    <option value="1">Uno</option>
                    <option value="2">Dos</option>
                    <option value="3">Tres</option>
                    <option value="4">Cuatro</option>
                </select>
                <br>
                <label>En tu dia a dia ¿sientes cansancio al realizar cualquier tarea?</label>
                <select name="respuesta19">
                    <option value="1">Uno</option>
                    <option value="2">Dos</option>
                    <option value="3">Tres</option>
                    <option value="4">Cuatro</option>
                </select>
                <br>
                <label>¿Has perdido el interes en el sexo (Relaciones sexuales)?</label>
                <select name="respuesta20">
                    <option value="1">Uno</option>
                    <option value="2">Dos</option>
                    <option value="3">Tres</option>
                    <option value="4">Cuatro</option>
                </select>
                <br>

                <label>Captura de video: </label>
                <video hidden id="video" autoplay></video>
               <input name="respuesta_video" type="file" id="id_respuesta_video" hidden>
            </div>

            <input hidden name="respuesta_emociones" value="">
           
            <button type="submit" id="submit"  name="submit">Guardar</button>

            <script>
                document.getElementById("boton").onclick = function () { myFunction() };

                function myFunction() {
                    alert("Comenzo el test")
                    document.getElementById("preguntas").hidden = false;
                    document.getElementById("boton").hidden = true;
                }


                
                let video = document.querySelector('#video');
                document.querySelector('#boton').addEventListener("click", function (ev) {
                    navigator.mediaDevices.getUserMedia({ audio: false, video: true })
                        .then(record)
                })

                let chunks = []

                function record(stream) {
                    video.srcObject = stream;

                    var mediaRecorder = new MediaRecorder(stream, {
                        mimeType: 'video/webm;codecs=h264'
                    })

                    mediaRecorder.start();
                    mediaRecorder.ondataavailable = function (e) {
                        chunks.push(e.data);
                    }

                    mediaRecorder.onstop = function () {
                        alert("Finalizo la grabacion");

                        let blob = new Blob(chunks, { type: "video/webm" });

                        chunks = [];
                        download(blob);
                    }

                


               

                function download(blob) {
                    document.getElementById("id_respuesta_video").src = blob;
                }

                document.querySelector('#submit').addEventListener("click", function (ev) {
                    mediaRecorder.stop
                    alert("Detenido")
                    
                })
                }
            </script>


            
        </form>
    </div>




</body>

</html>